//! Coverage and reporting tools.
//!
//! * `cr-coverage [--write PATH] [--check]` — which Comprehensive Rules are cited by tests
//!   (via `cr!(...)`) or exempted (`docs/cr-exemptions.tsv`).
//! * `card-coverage [--write PATH]` — how many cards the oracle compiler fully supports,
//!   and the most common unsupported ability texts.
//! * `rulings-coverage [--write PATH]` — which Scryfall rulings are cited by tests (via
//!   `ruling!(...)`).
//! * `unsupported [--limit N] [--filter TEXT]` — dump unsupported ability texts with counts.

use mtg_data::rules::RuleKind;
use regex::Regex;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::path::{Path, PathBuf};

fn repo_root() -> PathBuf {
    PathBuf::from(concat!(env!("CARGO_MANIFEST_DIR"), "/../.."))
}

fn rust_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(rd) = std::fs::read_dir(dir) else {
        return;
    };
    for e in rd.flatten() {
        let p = e.path();
        if p.is_dir() {
            if p.file_name().is_some_and(|n| n == "target" || n == ".git") {
                continue;
            }
            rust_files(&p, out);
        } else if p.extension().is_some_and(|x| x == "rs") {
            out.push(p);
        }
    }
}

/// All `cr!("...")` citations in the repository: rule id → files citing it.
pub fn cr_citations() -> BTreeMap<String, BTreeSet<String>> {
    let mut files = Vec::new();
    rust_files(&repo_root().join("crates"), &mut files);
    let macro_re = Regex::new(r#"(?s)cr!\s*\((.*?)\)"#).unwrap();
    let lit_re = Regex::new(r#""(\d{3}(?:\.\d+[a-z]*)?)""#).unwrap();
    let mut out: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for f in files {
        let Ok(text) = std::fs::read_to_string(&f) else {
            continue;
        };
        let rel = f
            .strip_prefix(repo_root())
            .unwrap_or(&f)
            .display()
            .to_string();
        for m in macro_re.captures_iter(&text) {
            for l in lit_re.captures_iter(&m[1]) {
                out.entry(l[1].to_string()).or_default().insert(rel.clone());
            }
        }
    }
    out
}

pub fn exemptions() -> BTreeMap<String, String> {
    let path = repo_root().join("docs/cr-exemptions.tsv");
    let mut out = BTreeMap::new();
    if let Ok(text) = std::fs::read_to_string(path) {
        for line in text.lines() {
            let l = line.trim();
            if l.is_empty() || l.starts_with('#') {
                continue;
            }
            if let Some((id, reason)) = l.split_once('\t') {
                out.insert(id.trim().to_string(), reason.trim().to_string());
            }
        }
    }
    out
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Status {
    Cited,
    ViaSubrules,
    Exempt,
    Uncovered,
}

fn cr_coverage(args: &[String]) {
    let rules = mtg_data::comprehensive_rules();
    let cites = cr_citations();
    let ex = exemptions();
    // Invalid citations.
    let invalid: Vec<&String> = cites.keys().filter(|id| rules.get(id).is_none()).collect();
    let mut status: HashMap<String, Status> = HashMap::new();
    // Compute bottom-up: process numbered rules in reverse document order.
    let numbered: Vec<&mtg_data::rules::Rule> = rules.numbered_rules().collect();
    for r in numbered.iter().rev() {
        let s = if cites.contains_key(&r.id) {
            Status::Cited
        } else if ex.contains_key(&r.id) {
            Status::Exempt
        } else if !r.children.is_empty()
            && r.children.iter().all(|c| {
                matches!(
                    status.get(c),
                    Some(Status::Cited | Status::ViaSubrules | Status::Exempt)
                )
            })
        {
            Status::ViaSubrules
        } else {
            Status::Uncovered
        };
        status.insert(r.id.clone(), s);
    }
    let total = numbered.len();
    let count = |s: Status| numbered.iter().filter(|r| status[&r.id] == s).count();
    let (cited, via, exempt, unc) = (
        count(Status::Cited),
        count(Status::ViaSubrules),
        count(Status::Exempt),
        count(Status::Uncovered),
    );
    let mut md = String::new();
    md.push_str(&format!(
        "# Comprehensive Rules coverage\n\nRules effective {}. Generated by `cargo run -p mtg-tools -- cr-coverage --write docs/CR_COVERAGE.md`.\n\n",
        rules.effective_date
    ));
    md.push_str("A rule is **cited** when a test calls `cr!(\"<rule>\")` (which also verifies the rule exists), **covered via subrules** when every subrule is covered, or **exempt** with a reason in `docs/cr-exemptions.tsv`.\n\n");
    md.push_str(&format!(
        "| | Rules | % |\n|---|---:|---:|\n| Cited by tests | {cited} | {:.1}% |\n| Covered via subrules | {via} | {:.1}% |\n| Exempt (with reason) | {exempt} | {:.1}% |\n| **Uncovered** | **{unc}** | {:.1}% |\n| Total numbered rules | {total} | |\n\n",
        100.0 * cited as f64 / total as f64,
        100.0 * via as f64 / total as f64,
        100.0 * exempt as f64 / total as f64,
        100.0 * unc as f64 / total as f64
    ));
    // Per section.
    md.push_str("## By section\n\n| Section | Title | Rules | Covered | Uncovered |\n|---|---|---:|---:|---:|\n");
    for sec in rules.all().filter(|r| r.kind == RuleKind::Section) {
        let rs: Vec<&&mtg_data::rules::Rule> = numbered
            .iter()
            .filter(|r| r.id.starts_with(&format!("{}.", sec.id)))
            .collect();
        let covered = rs
            .iter()
            .filter(|r| status[&r.id] != Status::Uncovered)
            .count();
        md.push_str(&format!(
            "| {} | {} | {} | {} | {} |\n",
            sec.id,
            sec.text,
            rs.len(),
            covered,
            rs.len() - covered
        ));
    }
    md.push_str("\n## Uncovered rules\n\n");
    for r in &numbered {
        if status[&r.id] == Status::Uncovered {
            let first = r.text.lines().next().unwrap_or("");
            let short: String = first.chars().take(140).collect();
            md.push_str(&format!("- **{}** {}\n", r.id, short));
        }
    }
    if !ex.is_empty() {
        md.push_str("\n## Exemptions\n\n");
        for (id, reason) in &ex {
            md.push_str(&format!("- **{id}**: {reason}\n"));
        }
    }
    let mut write = None;
    let mut check = false;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--write" => {
                write = Some(args[i + 1].clone());
                i += 1;
            }
            "--check" => check = true,
            _ => {}
        }
        i += 1;
    }
    println!(
        "CR coverage: {} cited, {} via subrules, {} exempt, {} uncovered of {} ({:.1}% covered)",
        cited,
        via,
        exempt,
        unc,
        total,
        100.0 * (total - unc) as f64 / total as f64
    );
    if !invalid.is_empty() {
        println!("INVALID citations (no such rule): {invalid:?}");
    }
    for (id, _) in &ex {
        if rules.get(id).is_none() {
            println!("INVALID exemption (no such rule): {id}");
        }
    }
    if let Some(p) = write {
        std::fs::write(repo_root().join(&p), md).expect("write report");
        println!("wrote {p}");
    }
    if check && (unc > 0 || !invalid.is_empty()) {
        std::process::exit(1);
    }
}

/// Normalizes ability text into a pattern: numbers → N, mana symbols kept.
fn pattern_of(text: &str) -> String {
    let re = Regex::new(r"\b\d+\b").unwrap();
    re.replace_all(text, "N").to_string()
}

fn card_coverage(args: &[String]) {
    use mtg_engine::card::CardDef;
    let db = mtg_data::cards();
    let mut total = 0usize;
    let mut full = 0usize;
    let mut total_abilities = 0usize;
    let mut supported_abilities = 0usize;
    let mut patterns: HashMap<String, usize> = HashMap::new();
    let mut by_format: BTreeMap<&str, (usize, usize)> = BTreeMap::new();
    let formats = [
        "standard",
        "pioneer",
        "modern",
        "legacy",
        "vintage",
        "commander",
        "pauper",
    ];
    for c in db.iter() {
        if !c.is_playable_card() || !c.is_legal_somewhere() {
            continue;
        }
        if c.games.iter().all(|g| g != "paper") && !c.games.is_empty() {
            continue;
        }
        total += 1;
        let def = CardDef::from_scryfall(c);
        let unsupported = def.unsupported_text();
        let n_abilities: usize = def.faces.iter().map(|f| f.chars.abilities.len()).sum();
        total_abilities += n_abilities;
        supported_abilities += n_abilities.saturating_sub(unsupported.len());
        let ok = unsupported.is_empty();
        if ok {
            full += 1;
        }
        for f in formats {
            if c.legality(f)
                .is_some_and(|l| l == "legal" || l == "restricted")
            {
                let e = by_format.entry(f).or_default();
                e.0 += 1;
                if ok {
                    e.1 += 1;
                }
            }
        }
        for u in unsupported {
            *patterns.entry(pattern_of(u)).or_default() += 1;
        }
    }
    let mut pats: Vec<(String, usize)> = patterns.into_iter().collect();
    pats.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
    println!(
        "Cards fully supported: {full}/{total} ({:.1}%); abilities supported: {supported_abilities}/{total_abilities} ({:.1}%)",
        100.0 * full as f64 / total.max(1) as f64,
        100.0 * supported_abilities as f64 / total_abilities.max(1) as f64
    );
    let mut md = String::new();
    md.push_str("# Card support coverage\n\nGenerated by `cargo run -p mtg-tools -- card-coverage --write docs/CARD_COVERAGE.md`. A card is *fully supported* when the oracle compiler understood every ability on every face.\n\n");
    md.push_str(&format!(
        "- Cards (paper, legal in at least one format): **{total}**\n- Fully supported: **{full}** ({:.1}%)\n- Abilities supported: {supported_abilities}/{total_abilities} ({:.1}%)\n\n",
        100.0 * full as f64 / total.max(1) as f64,
        100.0 * supported_abilities as f64 / total_abilities.max(1) as f64
    ));
    md.push_str("| Format | Cards | Fully supported | % |\n|---|---:|---:|---:|\n");
    for (f, (t, s)) in &by_format {
        md.push_str(&format!(
            "| {f} | {t} | {s} | {:.1}% |\n",
            100.0 * *s as f64 / (*t).max(1) as f64
        ));
    }
    md.push_str("\n## Most common unsupported ability texts\n\n| Count | Text |\n|---:|---|\n");
    for (p, n) in pats.iter().take(200) {
        md.push_str(&format!(
            "| {n} | {} |\n",
            p.replace('|', "\\|").replace('\n', " / ")
        ));
    }
    let mut i = 0;
    while i < args.len() {
        if args[i] == "--write" {
            std::fs::write(repo_root().join(&args[i + 1]), &md).expect("write report");
            println!("wrote {}", args[i + 1]);
            i += 1;
        }
        i += 1;
    }
}

fn unsupported(args: &[String]) {
    use mtg_engine::card::CardDef;
    let mut limit = 100usize;
    let mut filter: Option<String> = None;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--limit" => {
                limit = args[i + 1].parse().unwrap();
                i += 1;
            }
            "--filter" => {
                filter = Some(args[i + 1].to_lowercase());
                i += 1;
            }
            _ => {}
        }
        i += 1;
    }
    let mut patterns: HashMap<String, (usize, String)> = HashMap::new();
    for c in mtg_data::cards().iter() {
        if !c.is_playable_card() || !c.is_legal_somewhere() {
            continue;
        }
        let def = CardDef::from_scryfall(c);
        for u in def.unsupported_text() {
            if filter
                .as_ref()
                .is_some_and(|f| !u.to_lowercase().contains(f))
            {
                continue;
            }
            let e = patterns.entry(pattern_of(u)).or_insert((0, c.name.clone()));
            e.0 += 1;
        }
    }
    let mut pats: Vec<(String, (usize, String))> = patterns.into_iter().collect();
    pats.sort_by(|a, b| b.1 .0.cmp(&a.1 .0).then(a.0.cmp(&b.0)));
    for (p, (n, example)) in pats.into_iter().take(limit) {
        println!("{n}\t{}\t[{example}]", p.replace('\n', " / "));
    }
}

/// All `ruling!("Card", "text")` citations.
pub fn ruling_citations() -> Vec<(String, String, String)> {
    let mut files = Vec::new();
    rust_files(&repo_root().join("crates"), &mut files);
    let re =
        Regex::new(r#"(?s)ruling!\s*\(\s*"((?:[^"\\]|\\.)*)"\s*,\s*"((?:[^"\\]|\\.)*)"\s*,?\s*\)"#)
            .unwrap();
    let mut out = Vec::new();
    for f in files {
        let Ok(text) = std::fs::read_to_string(&f) else {
            continue;
        };
        let rel = f
            .strip_prefix(repo_root())
            .unwrap_or(&f)
            .display()
            .to_string();
        for m in re.captures_iter(&text) {
            out.push((
                m[1].replace("\\\"", "\""),
                m[2].replace("\\\"", "\""),
                rel.clone(),
            ));
        }
    }
    out
}

fn rulings_coverage(args: &[String]) {
    let cites = ruling_citations();
    let rulings = mtg_data::rulings();
    let cards = mtg_data::cards();
    let mut matched: BTreeSet<(String, String)> = BTreeSet::new(); // (oracle_id, comment)
    let mut unmatched = Vec::new();
    for (card, needle, file) in &cites {
        let Some(c) = cards.by_name(card) else {
            unmatched.push(format!("{card}: unknown card ({file})"));
            continue;
        };
        let n = mtg_data::normalize_text(needle);
        let mut found = false;
        for r in rulings.for_oracle_id(&c.oracle_id) {
            if mtg_data::normalize_text(&r.comment).contains(&n) {
                matched.insert((c.oracle_id.clone(), r.comment.clone()));
                found = true;
            }
        }
        if !found {
            unmatched.push(format!("{card}: {needle} ({file})"));
        }
    }
    let unique_comments: BTreeSet<&str> = rulings.iter().map(|r| r.comment.as_str()).collect();
    let cited_comments: BTreeSet<&str> = matched.iter().map(|(_, c)| c.as_str()).collect();
    // A ruling text shared by many cards counts as covered once for "unique" coverage.
    let covered_unique = unique_comments
        .iter()
        .filter(|c| cited_comments.contains(*c))
        .count();
    println!(
        "Rulings cited: {} (card, ruling) pairs; {} of {} unique ruling texts ({:.2}%); {} citations unmatched",
        matched.len(),
        covered_unique,
        unique_comments.len(),
        100.0 * covered_unique as f64 / unique_comments.len() as f64,
        unmatched.len()
    );
    for u in &unmatched {
        println!("  UNMATCHED {u}");
    }
    let mut md = String::new();
    md.push_str("# Scryfall rulings coverage\n\nGenerated by `cargo run -p mtg-tools -- rulings-coverage --write docs/RULINGS_COVERAGE.md`. Tests cite rulings with `ruling!(\"Card Name\", \"distinctive text\")`, which fails if no such ruling exists.\n\n");
    md.push_str(&format!(
        "- Total rulings: {} ({} unique texts across {} cards)\n- (card, ruling) pairs cited by tests: **{}**\n- Unique ruling texts covered: **{}** ({:.2}%)\n\n",
        rulings.len(),
        unique_comments.len(),
        rulings.iter().map(|r| r.oracle_id.as_str()).collect::<BTreeSet<_>>().len(),
        matched.len(),
        covered_unique,
        100.0 * covered_unique as f64 / unique_comments.len() as f64
    ));
    let mut by_card: BTreeMap<String, usize> = BTreeMap::new();
    for (card, _, _) in &cites {
        *by_card.entry(card.clone()).or_default() += 1;
    }
    md.push_str(&format!(
        "## Cards with cited rulings ({})\n\n",
        by_card.len()
    ));
    for (c, n) in &by_card {
        md.push_str(&format!("- {c} ({n})\n"));
    }
    let mut i = 0;
    while i < args.len() {
        if args[i] == "--write" {
            std::fs::write(repo_root().join(&args[i + 1]), &md).expect("write report");
            println!("wrote {}", args[i + 1]);
            i += 1;
        }
        i += 1;
    }
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    match args.first().map(String::as_str) {
        Some("cr-coverage") => cr_coverage(&args[1..]),
        Some("card-coverage") => card_coverage(&args[1..]),
        Some("rulings-coverage") => rulings_coverage(&args[1..]),
        Some("unsupported") => unsupported(&args[1..]),
        _ => {
            eprintln!("usage: mtg-tools <cr-coverage|card-coverage|rulings-coverage|unsupported> [--write PATH] [--check]");
            std::process::exit(2);
        }
    }
}
