//! Registry of keyword action implementations (CR 701).
//!
//! Each keyword action (or small family of related ones) lives in its own file in this
//! directory, implements [`KeywordActionRules`], and registers itself with
//! `inventory::submit! { KeywordActionRegistration(&X) }`. Files here are compiled as
//! modules automatically (see build.rs).
//!
//! [`Effect::KeywordAction`] is dispatched here first (see `keyword_actions.rs`); actions
//! that need more parameters than who/what/N (amass's Army subtype, the options of a
//! villainous choice or a vote) use [`Effect::KeywordActionEx`] with a [`Spec`].
//!
//! Rules hooks a keyword action needs outside its own instruction (a designation's
//! effects, "whenever [something] explores" triggers, conditions) are provided through
//! the keyword registry's global hooks (`kw::KeywordRules` with no keyword kinds).

use crate::ability::*;
use crate::eval::Ctx;
use crate::events::Event;
use crate::game::Game;
use crate::object::Zone;
use crate::types::*;
use serde::{Deserialize, Serialize};
use smol_str::SmolStr;
use std::sync::OnceLock;

/// The parameters of a keyword action instruction.
pub struct Args<'a> {
    pub action: KeywordAction,
    /// The player(s) performing it.
    pub who: &'a PlayerRef,
    /// The object(s) performing it or it's performed on.
    pub what: &'a Sel,
    /// Its number (explore N times, connive N, amass N, ...).
    pub n: &'a Value,
    /// Extra parameters, for [`Effect::KeywordActionEx`].
    pub spec: Option<&'a Spec>,
}

/// A keyword action with extra parameters ([`Effect::KeywordActionEx`]).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Spec {
    pub action: KeywordAction,
    pub who: PlayerRef,
    pub what: Sel,
    pub n: Value,
    /// A subtype: the [subtype] of "amass [subtype] N" (CR 701.47a).
    #[serde(default)]
    pub subtype: Option<Subtype>,
    /// Named options, each with the effect it stands for: the options of a villainous
    /// choice (CR 701.55a), or the choices of a vote (CR 701.38a).
    #[serde(default)]
    pub options: Vec<(String, Effect)>,
    /// The reverse of the action: a suspected creature becomes no longer suspected
    /// (CR 701.60a).
    #[serde(default)]
    pub undo: bool,
}

impl Spec {
    pub fn new(action: KeywordAction, who: PlayerRef, what: Sel, n: Value) -> Spec {
        Spec {
            action,
            who,
            what,
            n,
            subtype: None,
            options: vec![],
            undo: false,
        }
    }
    pub fn effect(self) -> Effect {
        Effect::KeywordActionEx(Box::new(self))
    }
}

/// State kept by keyword actions, in [`Game::kwa`].
#[derive(Clone, Debug, Default)]
pub struct KwaState {
    /// Cards exiled by airbending: while each remains exiled (the same object), its owner
    /// may cast it by paying {2} rather than its mana cost (CR 701.65a).
    pub airbent: Vec<ObjectId>,
    /// Earthbent lands (CR 701.66a): (land, player who earthbent it).
    pub earthbent: Vec<(ObjectId, PlayerId)>,
    /// Harnessed permanents (CR 701.64b). A permanent that leaves the battlefield becomes
    /// a new object (CR 400.7), which isn't harnessed.
    pub harnessed: Vec<ObjectId>,
    /// Exerted permanents and the player who exerted each (CR 701.43a).
    pub exerted_by: Vec<(ObjectId, PlayerId)>,
}

/// The rules of one or more keyword actions.
pub trait KeywordActionRules: Sync + Send {
    /// The keyword action(s) this implementation performs.
    fn actions(&self) -> &'static [KeywordAction];
    /// Performs the action as part of a resolving spell or ability (or another effect).
    fn perform(&self, g: &mut Game, args: &Args, ctx: &mut Ctx);
    /// Whether the player could choose to perform the action, when it's optional ("you
    /// may blight 1") or a cost (CR 118.3): not if they're unable to (e.g. CR 701.59b,
    /// 701.68b).
    fn can_choose(&self, _g: &Game, _args: &Args, _ctx: &Ctx) -> bool {
        true
    }
}

/// Registration of a keyword action implementation.
pub struct KeywordActionRegistration(pub &'static dyn KeywordActionRules);
inventory::collect!(KeywordActionRegistration);

// Every file in this directory is a module (generated by build.rs).
include!(concat!(env!("OUT_DIR"), "/kwa_mods.rs"));

/// All registered keyword action implementations.
pub fn registry() -> &'static [&'static dyn KeywordActionRules] {
    static R: OnceLock<Vec<&'static dyn KeywordActionRules>> = OnceLock::new();
    R.get_or_init(|| {
        inventory::iter::<KeywordActionRegistration>
            .into_iter()
            .map(|r| r.0)
            .collect()
    })
}

fn find(action: KeywordAction) -> Option<&'static dyn KeywordActionRules> {
    registry()
        .iter()
        .copied()
        .find(|r| r.actions().contains(&action))
}

/// Performs `action` if it's implemented here. Returns false if it isn't.
pub fn perform(
    g: &mut Game,
    action: KeywordAction,
    who: &PlayerRef,
    what: &Sel,
    n: &Value,
    ctx: &mut Ctx,
) -> bool {
    let Some(r) = find(action) else {
        return false;
    };
    let args = Args {
        action,
        who,
        what,
        n,
        spec: None,
    };
    r.perform(g, &args, ctx);
    true
}

/// Whether a player may choose to have the keyword action `e` performed (it's optional,
/// or part of a cost). `None` if `e` isn't a keyword action implemented here.
pub fn can_choose(g: &Game, e: &Effect, ctx: &Ctx) -> Option<bool> {
    let args = match e {
        Effect::KeywordAction {
            action,
            who,
            what,
            n,
        } => Args {
            action: *action,
            who,
            what,
            n,
            spec: None,
        },
        Effect::KeywordActionEx(spec) => Args {
            action: spec.action,
            who: &spec.who,
            what: &spec.what,
            n: &spec.n,
            spec: Some(spec),
        },
        _ => return None,
    };
    find(args.action).map(|r| r.can_choose(g, &args, ctx))
}

/// Performs a keyword action with extra parameters ([`Effect::KeywordActionEx`]).
pub fn perform_spec(g: &mut Game, spec: &Spec, ctx: &mut Ctx) {
    let args = Args {
        action: spec.action,
        who: &spec.who,
        what: &spec.what,
        n: &spec.n,
        spec: Some(spec),
    };
    match find(spec.action) {
        Some(r) => r.perform(g, &args, ctx),
        None => {
            crate::keyword_actions::perform(g, spec.action, &spec.who, &spec.what, &spec.n, ctx)
        }
    }
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Variables of the resolving ability set by keyword actions, for the instructions that
/// follow them.
pub mod kvars {
    use crate::ability::{vars, Var};
    /// "The Army you amassed" (CR 701.47c).
    pub const AMASSED: Var = vars::USER + 1047;
    /// "The discovered card" (CR 701.57c).
    pub const DISCOVERED: Var = vars::USER + 1057;
    /// "The blighted creature" (CR 701.68c).
    pub const BLIGHTED: Var = vars::USER + 1068;
    /// "The cards exiled this way" by airbending (CR 701.65a).
    pub const AIRBENT: Var = vars::USER + 1065;
}

/// Reports that a player performed a keyword action (for "whenever you [action]"
/// triggers, `TriggerCond::PlayerAction`).
pub fn emit(g: &mut Game, name: &str, player: PlayerId, obj: Option<ObjectId>, amount: i32) {
    g.emit(Event::Custom {
        name: SmolStr::new(name),
        player: Some(player),
        obj,
        amount,
    });
}

/// Whether `id` is (still) a permanent on the battlefield.
pub fn on_battlefield(g: &Game, id: ObjectId) -> bool {
    g.is_live(id) && g.obj(id).zone == Zone::Battlefield
}

/// The player who controls `id`, or, if it's no longer on the battlefield, who last
/// controlled it (its last known information, e.g. CR 701.44c, 701.50b).
pub fn controller_or_last(g: &Game, id: ObjectId) -> PlayerId {
    g.obj(id).controller
}

/// Picks which of `remaining` performs an action next when several objects are
/// instructed to perform it at the same time: the first player in APNAP order who
/// controls (or last controlled) one or more of them chooses one (CR 701.44d, 701.50c).
/// Removes and returns it.
pub fn next_in_apnap_order(
    g: &mut Game,
    remaining: &mut Vec<ObjectId>,
    source: Option<ObjectId>,
    prompt: &str,
) -> Option<ObjectId> {
    if remaining.is_empty() {
        return None;
    }
    let order = g.apnap();
    let chooser = order
        .iter()
        .copied()
        .find(|p| remaining.iter().any(|o| controller_or_last(g, *o) == *p))
        .unwrap_or_else(|| controller_or_last(g, remaining[0]));
    let mine: Vec<ObjectId> = remaining
        .iter()
        .copied()
        .filter(|o| controller_or_last(g, *o) == chooser)
        .collect();
    let pick = if mine.len() == 1 {
        mine[0]
    } else {
        g.ask_objects(chooser, source, prompt, mine.clone(), 1, 1)
            .first()
            .copied()
            .unwrap_or(mine[0])
    };
    remaining.retain(|o| *o != pick);
    Some(pick)
}

/// The number of an instruction (at least 0).
pub fn number(g: &Game, n: &Value, ctx: &Ctx) -> u32 {
    g.eval_value(n, ctx).max(0) as u32
}
