//! Rulings batch S22 — assorted rulings about casting spells: colored artifacts
//! (CR 105.2, 202.2), casting a commander from the command zone isn't casting it from a
//! hand (CR 903.8), "can't have or gain" abilities and effects of resolving spells
//! (CR 113.11), controlling another player (CR 723), miracle (CR 702.94), rebound and
//! buyback (CR 616.1), and abilities that trigger during a cleanup step (CR 514.3a).

use crate::r_s01_common::*;
use crate::r_s02_common::destroy;
use crate::r_s06_common::has_kw;
use crate::r_s13_common::{commander, commander_game};
use crate::r_s04_common::spell_targets;
use mtg_engine::decision::{Action, Answer, Decision};
use mtg_engine::keywords::KeywordKind;
use mtg_engine::object::{CastMethod, Zone};
use mtg_engine::testing::*;
use mtg_engine::turn::Step;
use mtg_engine::types::*;
use mtg_engine::*;

#[test]
fn glaze_fiend_a_colored_artifact_is_colored_everywhere_and_still_an_artifact() {
    cr!("105.2", "202.2", "301.1");
    ruling!(
        "Glaze Fiend",
        "The only difference between a colored artifact and a colorless artifact is, obviously, its color. Unlike most artifacts, a colored artifact requires colored mana to cast. Also unlike most artifacts, a colored artifact has a color in all zones. It will interact with cards that care about color. Other than that, a colored artifact behaves just like any other artifact. It will interact as normal with any card that cares about artifacts, such as Shatter or Arcbound Ravager."
    );
    supported("Glaze Fiend");
    // Glaze Fiend {1}{B}: a black artifact creature.
    let mut t = TestGame::new(2);
    let fiend = t.hand(P0, "Glaze Fiend");
    assert!(t.obj(fiend).chars.colors.contains(Color::Black));
    // Colored mana is needed: two Wastes can't cast it.
    t.lands(P0, "Wastes", 2);
    assert!(t.cast(P0, fiend).try_go().is_err());
    t.lands(P0, "Swamp", 1);
    t.cast(P0, fiend).go();
    t.resolve_all();
    let fiend = t.named_on_battlefield("Glaze Fiend")[0];
    assert!(t.obj(fiend).chars.colors.contains(Color::Black));
    // Doom Blade ("Destroy target nonblack creature.") can't target it.
    assert!(!spell_targets(&mut t, P1, "Doom Blade").contains(&Entity::Object(fiend)));
    // Shatter ("Destroy target artifact.") can.
    assert!(spell_targets(&mut t, P1, "Shatter").contains(&Entity::Object(fiend)));
    // Arcbound Ravager ("Sacrifice an artifact: Put a +1/+1 counter on this creature.")
    // can sacrifice it; in the graveyard it's still black.
    // (It enters with its modular +1/+1 counter; Glaze Fiend's ability triggers.)
    let ravager = t.enter(P0, "Arcbound Ravager");
    t.resolve_all();
    let n = ravager_counters(&t, ravager);
    assert_eq!(n, 1);
    t.answer_choose(P0, &[Entity::Object(fiend)]);
    t.activate(P0, ravager, 0, &[]).expect("sacrifice an artifact");
    t.resolve_all();
    assert!(t.in_graveyard(P0, "Glaze Fiend"));
    assert_eq!(ravager_counters(&t, ravager), n + 1);
    let dead = t.g.find_in_zone(Zone::Graveyard(P0), "Glaze Fiend")[0];
    assert!(t.obj(dead).chars.colors.contains(Color::Black));
}

fn ravager_counters(t: &TestGame, id: ObjectId) -> u32 {
    t.counters(id, "+1/+1")
}

#[test]
fn myojin_cast_from_the_command_zone_isnt_cast_from_hand() {
    cr!("903.8", "601.2a");
    ruling!(
        "Myojin of Life's Web",
        "In a Commander game where this card is your commander, casting it from the Command zone does not count as casting it from your hand."
    );
    supported("Myojin of Life's Web");
    // "Myojin of Life's Web enters with a divinity counter on it if you cast it from your
    // hand."
    let mut t = commander_game();
    let myojin = commander(&mut t, P0, "Myojin of Life's Web");
    t.lands(P0, "Forest", 9);
    t.cast(P0, myojin).go();
    t.resolve_all();
    let m = t.named_on_battlefield("Myojin of Life's Web")[0];
    assert_eq!(t.counters(m, "divinity"), 0);
    assert!(!has_kw(&t, m, KeywordKind::Indestructible));
    // Cast from the hand, it gets the counter.
    let mut t = commander_game();
    t.lands(P0, "Forest", 9);
    let myojin = t.hand(P0, "Myojin of Life's Web");
    t.cast(P0, myojin).go();
    t.resolve_all();
    let m = t.named_on_battlefield("Myojin of Life's Web")[0];
    assert_eq!(t.counters(m, "divinity"), 1);
}

#[test]
fn archetype_of_courage_a_resolved_grant_of_first_strike_never_applies() {
    cr!("113.11", "611.2c", "613.1f");
    ruling!(
        "Archetype of Courage",
        "While you control an Archetype, continuous effects generated by the resolution of spells and abilities that would give the specified ability to creatures your opponents control aren’t created."
    );
    supported("Archetype of Courage");
    supported("Sure Strike");
    // P1's Sure Strike ("Target creature gets +3/+0 and gains first strike until end of
    // turn.") on their Grizzly Bears while P0 controls Archetype of Courage: +3/+0 only,
    // and still no first strike after the Archetype leaves the battlefield that turn.
    let mut t = TestGame::new(2);
    let archetype = t.battlefield(P0, "Archetype of Courage");
    let bears = t.battlefield(P1, "Grizzly Bears");
    t.set_step(P1, Step::PrecombatMain);
    t.lands(P1, "Mountain", 2);
    let strike = t.hand(P1, "Sure Strike");
    t.cast(P1, strike).target(Entity::Object(bears)).go();
    t.resolve_all();
    t.g.recompute();
    assert_eq!(t.pt(bears), (5, 2));
    assert!(!has_kw(&t, bears, KeywordKind::FirstStrike));
    destroy(&mut t, archetype);
    t.g.recompute();
    assert!(!has_kw(&t, bears, KeywordKind::FirstStrike));
    assert_eq!(t.pt(bears), (5, 2));
    // Another Sure Strike, now that the Archetype is gone: first strike.
    let strike = t.hand(P1, "Sure Strike");
    t.lands(P1, "Mountain", 2);
    t.cast(P1, strike).target(Entity::Object(bears)).go();
    t.resolve_all();
    t.g.recompute();
    assert!(has_kw(&t, bears, KeywordKind::FirstStrike));
}

#[test]
fn worst_fears_the_controller_makes_all_the_controlled_players_decisions() {
    cr!("723.5", "723.1");
    ruling!(
        "Worst Fears",
        "While controlling another player, you make all choices and decisions that player is allowed to make or is told to make during that turn. This includes choices about what spells to cast or what abilities to activate, as well as any decisions called for by triggered abilities or for any other reason."
    );
    supported("Worst Fears");
    supported("Flametongue Kavu");
    // P0 casts Worst Fears ("You control target player during that player's next turn.")
    // on P1. During P1's turn, P0 has P1 cast P1's Flametongue Kavu, and chooses the
    // target of its triggered ability ("it deals 4 damage to target creature"): P1's own
    // Hill Giant.
    let mut t = TestGame::new(2);
    t.lands(P0, "Swamp", 8);
    let fears = t.hand(P0, "Worst Fears");
    t.cast(P0, fears).target(Entity::Player(P1)).go();
    t.resolve_all();
    let giant = t.battlefield(P1, "Hill Giant");
    let mine = t.battlefield(P0, "Grizzly Bears");
    t.lands(P1, "Mountain", 4);
    let kavu = t.hand(P1, "Flametongue Kavu");
    t.advance_to(P1, Step::PrecombatMain);
    assert_eq!(mtg_engine::player_control::decider(&t.g, P1), P0);
    let from = t.asked().len();
    t.answer(
        P0,
        DecisionKind::Priority,
        Answer::Action(Action::Cast {
            card: kavu,
            method: CastMethod::Normal,
        }),
    );
    t.answer_targets(P0, &[Entity::Object(giant)]);
    let ok = t
        .g
        .run_until(1000, |g| !g.find_in_zone(Zone::Graveyard(P1), "Hill Giant").is_empty());
    assert!(ok);
    assert!(t.on_battlefield(mine));
    assert_eq!(t.named_on_battlefield("Flametongue Kavu").len(), 1);
    // The target choice for P1's trigger was asked of P0's agent on P1's behalf.
    assert!(t.asked()[from..]
        .iter()
        .any(|(p, d)| *p == P1 && matches!(d, Decision::ChooseTargets { .. })));
}

#[test]
fn lorehold_miracle_is_an_alternative_cost_additional_costs_still_apply() {
    cr!("702.94a", "118.9a", "118.8", "601.2b");
    ruling!(
        "Lorehold, the Historian",
        "Miracle is an alternative cost to cast the spell with miracle. It can't be combined with other alternative costs, such as casting a spell \"without paying its mana cost.\" You may, however, pay additional costs, such as kicker. If the spell has any mandatory additional costs, those must be paid to cast the spell."
    );
    supported("Lorehold, the Historian");
    // "Each instant and sorcery card in your hand has miracle {2}." The first card P0
    // draws this turn is revealed and cast for its miracle cost.
    let miracle = |top: &str, lands: usize, setup: fn(&mut TestGame)| {
        let mut t = TestGame::new(2);
        t.battlefield(P0, "Lorehold, the Historian");
        t.lands(P0, "Mountain", lands);
        setup(&mut t);
        let card = t.library_top(P0, top);
        t.answer_yes(P0, true); // reveal
        t.answer_yes(P0, true); // cast
        (t, card)
    };
    // Kicker can be paid on top of the miracle cost: {2} + {4}.
    let (mut t, card) = miracle("Burst Lightning", 6, |_| {});
    t.answer(P0, DecisionKind::OptionalCost, Answer::Bool(true));
    t.answer_targets(P0, &[Entity::Player(P1)]);
    t.g.draw_cards(P0, 1);
    t.resolve_all();
    assert_eq!(t.life(P1), 16);
    assert_eq!(tapped_lands(&t, P0), 6);
    assert!(t.in_graveyard(P0, "Burst Lightning"));
    let _ = card;
    // A mandatory additional cost must be paid: Village Rites needs a creature to
    // sacrifice (Lorehold itself is one: here P0 sacrifices Grizzly Bears).
    let (mut t, _) = miracle("Village Rites", 2, |t| {
        t.battlefield(P0, "Grizzly Bears");
    });
    let bears = t.named_on_battlefield("Grizzly Bears")[0];
    t.answer_choose(P0, &[Entity::Object(bears)]);
    let lib = t.library_size(P0);
    t.g.draw_cards(P0, 1);
    t.resolve_all();
    assert!(t.in_graveyard(P0, "Grizzly Bears"));
    assert_eq!(t.library_size(P0), lib - 1 - 2);
    // No other alternative cost: Cyclonic Rift cast for its miracle cost isn't
    // overloaded.
    let (mut t, _) = miracle("Cyclonic Rift", 9, |t| {
        t.battlefield(P1, "Grizzly Bears");
        t.battlefield(P1, "Hill Giant");
    });
    let bears = t.named_on_battlefield("Grizzly Bears")[0];
    t.answer_targets(P0, &[Entity::Object(bears)]);
    t.g.draw_cards(P0, 1);
    t.resolve_all();
    assert!(t.in_hand(P1, "Grizzly Bears"));
    assert_eq!(t.named_on_battlefield("Hill Giant").len(), 1);
    assert_eq!(tapped_lands(&t, P0), 2);
}

#[test]
fn cast_through_time_rebound_and_buyback_its_controller_chooses() {
    cr!("702.88a", "702.27a", "616.1");
    ruling!(
        "Cast Through Time",
        "If a spell you cast from your hand has both rebound and buyback (and the buyback cost was paid), you choose which effect to apply as it resolves."
    );
    supported("Cast Through Time");
    supported("Capsize");
    // Capsize {1}{U}{U}, buyback {3}: "Return target permanent to its owner's hand."
    // With Cast Through Time, it has rebound too.
    let run = |choice: usize| {
        let mut t = TestGame::new(2);
        t.battlefield(P0, "Cast Through Time");
        let bears = t.battlefield(P1, "Grizzly Bears");
        t.lands(P0, "Island", 6);
        let capsize = t.hand(P0, "Capsize");
        t.answer(P0, DecisionKind::OptionalCost, Answer::Bool(true));
        t.answer(P0, DecisionKind::Replacement, Answer::Index(choice));
        t.answer(P0, DecisionKind::Option, Answer::Index(choice));
        let from = t.asked().len();
        t.cast(P0, capsize).target(Entity::Object(bears)).go();
        t.resolve_all();
        assert!(t.in_hand(P1, "Grizzly Bears"));
        let asked = t.asked()[from..]
            .iter()
            .filter(|(p, d)| {
                *p == P0
                    && matches!(
                        d,
                        Decision::ChooseReplacement { .. } | Decision::ChooseOption { .. }
                    )
            })
            .count();
        assert!(asked >= 1, "P0 chose which to apply");
        (t.in_hand(P0, "Capsize"), t.in_exile("Capsize"))
    };
    let a = run(0);
    let b = run(1);
    // One choice returns it to P0's hand (buyback), the other exiles it (rebound).
    let mut outcomes = vec![a, b];
    outcomes.sort();
    assert_eq!(outcomes, vec![(false, true), (true, false)]);
}

#[test]
fn archfiend_of_ifnir_a_discard_in_cleanup_triggers_and_players_get_priority() {
    cr!("514.1", "514.3a");
    ruling!(
        "Archfiend of Ifnir",
        "If a player discards a card during their cleanup step due to having too many cards in hand, any appropriate abilities that trigger on discarding that card trigger. If this happens, those triggered abilities are put onto the stack and players receive priority in that cleanup step to cast spells or activate abilities (normally, no players may take actions during a cleanup step). Another cleanup step is created following that one."
    );
    supported("Archfiend of Ifnir");
    // "Whenever you cycle or discard another card, put a -1/-1 counter on each creature
    // your opponents control." P0 ends the turn with eight cards in hand.
    let mut t = TestGame::new(2);
    t.battlefield(P0, "Archfiend of Ifnir");
    let elves = t.battlefield(P1, "Llanowar Elves");
    let giant = t.battlefield(P1, "Hill Giant");
    for _ in 0..8 {
        t.hand(P0, "Forest");
    }
    let turn = t.g.turn.number;
    let cleanup_priority = watch(
        &mut t,
        P1,
        |d| matches!(d, Decision::Priority { .. }),
        |g| (g.turn.step, g.turn.number, g.stack.len()),
    );
    t.advance_to(P1, Step::Upkeep);
    assert_eq!(t.hand_size(P0), 7);
    // The trigger resolved during P0's turn: the Elves died, the Giant has a counter.
    assert!(t.in_graveyard(P1, "Llanowar Elves"));
    assert_eq!(t.counters(giant, "-1/-1"), 1);
    let seen = cleanup_priority.lock().unwrap().clone();
    assert!(
        seen.iter()
            .any(|(step, n, stack)| *step == Step::Cleanup && *n == turn && *stack == 1),
        "P1 got priority in the cleanup step with the trigger on the stack: {seen:?}"
    );
    let _ = elves;
}

#[test]
fn discontinuity_triggers_while_ending_the_turn_go_on_the_stack_in_cleanup() {
    cr!("724.1", "724.1d", "514.3a");
    ruling!(
        "Discontinuity",
        "If any triggered abilities do trigger during this process, they're put onto the stack during the cleanup step. If this happens, players will have a chance to cast spells and activate abilities, then there will be another cleanup step before the turn is over."
    );
    supported("Discontinuity");
    // P0 ends the turn with Discontinuity ("End the turn.") holding nine cards; the
    // discard to hand size triggers Archfiend of Ifnir.
    let mut t = TestGame::new(2);
    t.battlefield(P0, "Archfiend of Ifnir");
    let giant = t.battlefield(P1, "Hill Giant");
    for _ in 0..9 {
        t.hand(P0, "Forest");
    }
    t.lands(P0, "Island", 4);
    let disc = t.hand(P0, "Discontinuity");
    let turn = t.g.turn.number;
    let seen = watch(
        &mut t,
        P1,
        |d| matches!(d, Decision::Priority { .. }),
        |g| (g.turn.step, g.turn.number, g.stack.len()),
    );
    t.answer(
        P0,
        DecisionKind::Priority,
        Answer::Action(Action::Cast {
            card: disc,
            method: CastMethod::Normal,
        }),
    );
    t.advance_to(P1, Step::Upkeep);
    assert_eq!(t.hand_size(P0), 7);
    // Two cards were discarded: two triggers, resolved during P0's turn.
    assert_eq!(t.counters(giant, "-1/-1"), 2);
    let seen = seen.lock().unwrap().clone();
    assert!(
        seen.iter()
            .any(|(step, n, stack)| *step == Step::Cleanup && *n == turn && *stack >= 1),
        "{seen:?}"
    );
}

#[test]
fn cast_through_time_a_spell_gained_control_of_has_rebound_that_does_nothing() {
    cr!("702.88a", "110.2", "115.7");
    ruling!(
        "Cast Through Time",
        "if you gain control of an instant or sorcery spell with Commandeer, it will have rebound, but the ability won’t do anything because that spell wasn’t cast from your hand."
    );
    supported("Cast Through Time");
    supported("Commandeer");
    // P1 casts Lightning Bolt at P0; P0 gains control of it with Commandeer ("Gain
    // control of target noncreature spell. You may choose new targets for it.") and
    // changes its target to P1.
    let mut t = TestGame::new(2);
    t.battlefield(P0, "Cast Through Time");
    crate::r_s04_common::add_mana(&mut t, P1, mtg_engine::mana::ManaType::R, 1);
    let bolt = t.hand(P1, "Lightning Bolt");
    let bolt = t.cast(P1, bolt).target(Entity::Player(P0)).go();
    assert!(!t
        .obj_now(bolt)
        .has_keyword(mtg_engine::keywords::KeywordKind::Rebound));
    crate::r_s04_common::add_mana(&mut t, P0, mtg_engine::mana::ManaType::U, 7);
    let commandeer = t.hand(P0, "Commandeer");
    t.cast(P0, commandeer).target(Entity::Object(bolt)).go();
    t.answer_yes(P0, true);
    t.answer_targets(P0, &[Entity::Player(P1)]);
    t.resolve();
    assert_eq!(t.obj_now(bolt).controller, P0);
    assert!(
        t.obj_now(bolt)
            .has_keyword(mtg_engine::keywords::KeywordKind::Rebound),
        "a spell P0 controls has rebound"
    );
    t.resolve_all();
    assert_eq!(t.life(P1), 17);
    assert_eq!(t.life(P0), 20);
    // It wasn't cast from P0's hand: it goes to its owner's graveyard, not exile.
    assert!(t.in_graveyard(P1, "Lightning Bolt"));
    assert!(!t.in_exile("Lightning Bolt"));
}

#[test]
fn spells_you_control_have_deathtouch_applies_to_a_spell_gained_control_of() {
    cr!("611.3a", "702.2b", "110.2");
    supported("Pestilent Spirit");
    supported("Commandeer");
    // "Instant and sorcery spells you control have deathtouch." is a continuous effect
    // (not one spells gain as they're cast, CR 610.5): P1's Shock, now controlled by P0,
    // has deathtouch, and its 2 damage destroys P1's Hill Giant.
    let mut t = TestGame::new(2);
    t.battlefield(P0, "Pestilent Spirit");
    let giant = t.battlefield(P1, "Hill Giant");
    crate::r_s04_common::add_mana(&mut t, P1, mtg_engine::mana::ManaType::R, 1);
    let shock = t.hand(P1, "Shock");
    let shock = t.cast(P1, shock).target(Entity::Player(P0)).go();
    crate::r_s04_common::add_mana(&mut t, P0, mtg_engine::mana::ManaType::U, 7);
    let commandeer = t.hand(P0, "Commandeer");
    t.cast(P0, commandeer).target(Entity::Object(shock)).go();
    t.answer_yes(P0, true);
    t.answer_targets(P0, &[Entity::Object(giant)]);
    t.resolve();
    assert!(t
        .obj_now(shock)
        .has_keyword(mtg_engine::keywords::KeywordKind::Deathtouch));
    t.resolve_all();
    assert!(!t.on_battlefield(giant));
    assert!(t.in_graveyard(P1, "Hill Giant"));
    assert_eq!(t.life(P0), 20);
}
