//! Rulings batch S20 — Auras: "enchanted" creatures (CR 303.4b) and Auras' static
//! abilities resuming when an effect that stopped them ends (CR 611.3a, 613.1f).

use crate::r_s01_common::*;
use crate::r_s02_common::destroy;
use crate::r_s04_common::ability_targets;
use crate::r_s06_common::{attach_new, has_kw};
use mtg_engine::keywords::KeywordKind;
use mtg_engine::testing::*;
use mtg_engine::*;

#[test]
fn an_auras_granted_flying_resumes_when_archetype_of_imagination_leaves() {
    cr!("611.3a", "613.1f");
    ruling!(
        "Archetype of Imagination",
        "Conversely, continuous effects generated by static abilities (such as an Aura that granted the appropriate ability) would resume applying if the Archetype left the battlefield."
    );
    supported("Archetype of Imagination");
    supported("Arcane Flight");
    let mut t = TestGame::new(2);
    // Arcane Flight: "Enchanted creature gets +1/+1 and has flying."
    let bears = t.battlefield(P1, "Grizzly Bears");
    attach_new(&mut t, P1, "Arcane Flight", bears);
    assert!(has_kw(&t, bears, KeywordKind::Flying));
    // "Creatures your opponents control lose flying and can't have or gain flying."
    let archetype = t.battlefield(P0, "Archetype of Imagination");
    t.g.recompute();
    assert!(!has_kw(&t, bears, KeywordKind::Flying));
    assert_eq!(t.pt(bears), (3, 3));
    destroy(&mut t, archetype);
    t.g.recompute();
    assert!(has_kw(&t, bears, KeywordKind::Flying));
}

#[test]
fn a_creature_is_enchanted_if_it_has_any_aura_attached() {
    cr!("303.4b");
    ruling!(
        "Ramses Overdark",
        "A creature is “enchanted” if it has any Auras attached to it."
    );
    supported("Ramses Overdark");
    let mut t = TestGame::new(2);
    // "{T}: Destroy target enchanted creature."
    let ramses = t.battlefield(P0, "Ramses Overdark");
    // An Aura its own controller controls, an Aura an opponent controls, an Equipment,
    // and nothing.
    let own_aura = t.battlefield(P1, "Grizzly Bears");
    attach_new(&mut t, P1, "Arcane Flight", own_aura);
    let their_aura = t.battlefield(P1, "Hill Giant");
    attach_new(&mut t, P0, "Pacifism", their_aura);
    let equipped = t.battlefield(P1, "Gray Ogre");
    attach_new(&mut t, P1, "Leonin Scimitar", equipped);
    let plain = t.battlefield(P1, "Llanowar Elves");
    let targets = ability_targets(&mut t, ramses, 0);
    assert!(targets.contains(&Entity::Object(own_aura)));
    assert!(targets.contains(&Entity::Object(their_aura)));
    assert!(!targets.contains(&Entity::Object(equipped)));
    assert!(!targets.contains(&Entity::Object(plain)));
    t.activate(P0, ramses, 0, &[Entity::Object(their_aura)])
        .expect("activate");
    t.resolve_all();
    assert!(!t.on_battlefield(their_aura));
}
