//! Hand-written ("manual") card abilities.
//!
//! The Oracle compiler ([`crate::oracle`]) covers every construct that two or more cards
//! share. A genuinely unique ability — one no other card's text shares — may instead be
//! written directly in the ability AST here, with engine hooks where the AST can't express
//! its rule.
//!
//! # Policy
//!
//! * **Compile first.** Hand-written definitions are only for genuine one-offs. Any
//!   construct shared by two or more cards must be compiled (an oracle pattern, a keyword,
//!   an AST node). `manual-check` fails when the compiler can parse a block on its own,
//!   so the definition must then be deleted.
//! * **Per ability, not per card.** A [`ManualAbility`] replaces exactly one normalized
//!   ability block of one face (the text the compiler reports in `FaceDef::unsupported`
//!   without it: reminder text stripped, self-references `~`, numbers as printed; print it
//!   with `mtg-tools unsupported --card "Name" --raw`). The card's other abilities still
//!   compile. Matching is by exact text, so an Oracle update makes the definition stale and
//!   the block reverts to unsupported (and `manual-check` reports it).
//! * **Every entry states its reason** (shown in `docs/CARD_COVERAGE.md`) **and every
//!   manual card has a test** in `tests/cards/m_<card>.rs` that loads the card by name and
//!   checks the hand-written behavior in a game.
//! * Hand-written abilities are verified by their tests, not by the Oracle round-trip
//!   renderer: it reports them as "manual", not as mismatches.
//!
//! # Adding one
//!
//! Add `src/cards/<snake_case_card_name>.rs` (auto-included by `build.rs`):
//!
//! ```ignore
//! use super::ManualAbility;
//! inventory::submit! { ManualAbility {
//!     card: "Trinisphere", face: 0,
//!     text: "As long as ~ is untapped, each spell ...",
//!     build: |_ctx| vec![ /* Ability values */ ],
//!     reason: "cost floor of three mana: unique cost rule",
//! } }
//! ```
//!
//! For rules the AST can't express, the file may also implement
//! [`crate::kw::KeywordRules`] with `kinds() -> &[]` and register it with
//! `inventory::submit! { KeywordRegistration(&X) }`: it then receives the registry-wide
//! hooks (`custom_effect`, `custom_condition`, `custom_trigger`, `custom_value`,
//! `custom_filter`, `state_based_actions`, `combat_damage_assigner`, `activation_cost`,
//! ...). Name custom hooks `card:<Card Name>:<what>` and reference them from the AST
//! (`Effect::Custom`, `StaticEffect::Custom`, ...). Hooks find their source permanents by
//! the custom ability on the object, never by name, so copies and text changes behave.

use crate::ability::{Ability, AbilityKind, StaticEffect};
use crate::game::Game;
use crate::oracle::CompileContext;
use crate::types::ObjectId;

/// A hand-written definition of one ability block of a card face.
pub struct ManualAbility {
    /// Oracle card name (the full name for multi-face cards).
    pub card: &'static str,
    /// Face/half index (0 = front/left).
    pub face: usize,
    /// The exact normalized ability block it replaces.
    pub text: &'static str,
    /// Builds the abilities.
    pub build: fn(&CompileContext) -> Vec<Ability>,
    /// Why this is hand-written (shown in reports).
    pub reason: &'static str,
}
inventory::collect!(ManualAbility);

// Every file in this directory is a module (generated by build.rs).
include!(concat!(env!("OUT_DIR"), "/card_mods.rs"));

/// All registered hand-written abilities.
pub fn all() -> impl Iterator<Item = &'static ManualAbility> {
    inventory::iter::<ManualAbility>.into_iter()
}

/// The hand-written definition of `block` on face `face` of the card `full_name`.
pub fn lookup(full_name: &str, face: usize, block: &str) -> Option<&'static ManualAbility> {
    all().find(|m| m.card == full_name && m.face == face && m.text == block)
}

/// A static ability that does nothing by itself but marks its object as having a rule a
/// hook implements (`StaticEffect::Custom(name)`), with its oracle text.
pub fn marker(name: &str, text: &str) -> Ability {
    crate::ability::AbilityDef::new(
        AbilityKind::Static(crate::ability::StaticAbility::new(StaticEffect::Custom(
            name.into(),
        ))),
        text,
    )
}

/// Whether the object has an ability built by [`marker`] with this name.
pub fn has_marker(g: &Game, id: ObjectId, name: &str) -> bool {
    g.obj(id).chars.abilities.iter().any(|a| is_marker(a, name))
}

/// Whether the ability is a [`marker`] with this name.
pub fn is_marker(a: &Ability, name: &str) -> bool {
    matches!(&a.kind, AbilityKind::Static(s) if matches!(&s.effect, StaticEffect::Custom(n) if n == name))
}

/// The functioning [`marker`] abilities named `name` (their conditions true), with their
/// sources and controllers, from the active statics (CR 604).
pub fn active(g: &Game, name: &str) -> Vec<(ObjectId, crate::types::PlayerId)> {
    g.statics
        .customs
        .iter()
        .filter(|(_, _, n)| n == name)
        .map(|(s, c, _)| (*s, *c))
        .collect()
}

/// A marker with a condition ("As long as ~ is untapped, ...").
pub fn marker_if(name: &str, cond: crate::ability::Condition, text: &str) -> Ability {
    let mut s = crate::ability::StaticAbility::new(StaticEffect::Custom(name.into()));
    s.condition = Some(cond);
    crate::ability::AbilityDef::new(AbilityKind::Static(s), text)
}

/// Checks the hand-written definitions against the card data and the tests in
/// `tests_cards_dir` (the `tests/cards/` directory): returns one message per problem.
///
/// * a definition matching no block of its card (stale: the Oracle text changed),
/// * a block the compiler can now parse on its own (delete the definition),
/// * a manual card with no test in `tests/cards/` naming it (`"Card Name"`),
/// * two definitions claiming the same block.
pub fn manual_check(tests_cards_dir: &std::path::Path) -> Vec<String> {
    let mut problems = Vec::new();
    let mut tests = String::new();
    if let Ok(rd) = std::fs::read_dir(tests_cards_dir) {
        for e in rd.flatten() {
            if e.path().extension().is_some_and(|x| x == "rs") {
                tests.push_str(&std::fs::read_to_string(e.path()).unwrap_or_default());
            }
        }
    }
    let entries: Vec<&ManualAbility> = all().collect();
    for (i, m) in entries.iter().enumerate() {
        if entries[..i]
            .iter()
            .any(|o| o.card == m.card && o.face == m.face && o.text == m.text)
        {
            problems.push(format!(
                "{} (face {}): two definitions claim {:?}",
                m.card, m.face, m.text
            ));
        }
        let Some(sc) = mtg_data::cards().by_name(m.card) else {
            problems.push(format!("{}: no such card", m.card));
            continue;
        };
        if sc.name != m.card {
            problems.push(format!("{}: use the full Oracle name {:?}", m.card, sc.name));
        }
        let def = crate::card::CardDef::from_scryfall(sc);
        if !def
            .faces
            .get(m.face)
            .is_some_and(|f| f.manual.iter().any(|t| t == m.text))
        {
            problems.push(format!(
                "{} (face {}): stale, matches no ability block: {:?}",
                m.card, m.face, m.text
            ));
            continue;
        }
        let plain = crate::oracle::without_manual(|| crate::card::CardDef::from_scryfall(sc));
        if !plain.faces[m.face].unsupported.iter().any(|t| t == m.text) {
            problems.push(format!(
                "{} (face {}): the compiler now parses {:?}; delete the hand-written definition",
                m.card, m.face, m.text
            ));
        }
        if !tests.contains(&format!("{:?}", m.card)) {
            problems.push(format!(
                "{}: no test in tests/cards/ loads this card by name",
                m.card
            ));
        }
    }
    problems
}
